//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestTransferContext : DbContext
    {
        public TestTransferContext()
            : base("name=TestTransferContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TransferOrder> TransferOrders { get; set; }
        public virtual DbSet<TransferOrderArrival> TransferOrderArrivals { get; set; }
        public virtual DbSet<TransferOrderLoader> TransferOrderLoaders { get; set; }
        public virtual DbSet<TransferOrderPlanning> TransferOrderPlannings { get; set; }
        public virtual DbSet<TransferOrderService> TransferOrderServices { get; set; }
        public virtual DbSet<TransferSubType> TransferSubTypes { get; set; }
        public virtual DbSet<TransferType> TransferTypes { get; set; }
    }
}
