//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferOrderService
    {
        public long transferOrderServiceId { get; set; }
        public long transferOrderId { get; set; }
        public long serviceId { get; set; }
        public long uomId { get; set; }
        public System.DateTime activityDate { get; set; }
        public decimal quantity { get; set; }
        public Nullable<decimal> factor { get; set; }
        public string authorizedBy { get; set; }
        public string comment { get; set; }
        public bool isVoided { get; set; }
        public System.DateTime inputDate { get; set; }
        public string inputBy { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> interfaceDate { get; set; }
    }
}
