//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferOrderLoader
    {
        public long transferOrderLoaderId { get; set; }
        public string loaderName { get; set; }
        public long siteId { get; set; }
        public bool isActive { get; set; }
        public System.DateTime inputDate { get; set; }
        public string inputBy { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string modifiedBy { get; set; }
    }
}
