//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferOrderPlanning
    {
        public long transferOrderPlanningId { get; set; }
        public Nullable<long> transferOrderId { get; set; }
        public long equipmentTripId { get; set; }
        public long productId { get; set; }
        public long equipmentId { get; set; }
        public Nullable<int> sequenceNumber { get; set; }
        public Nullable<decimal> planVolume { get; set; }
        public Nullable<decimal> planWeight { get; set; }
        public string sealNumber { get; set; }
        public bool isSelected { get; set; }
        public bool isVoided { get; set; }
        public System.DateTime inputDate { get; set; }
        public string inputBy { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<decimal> availableWeight { get; set; }
        public Nullable<decimal> availableVolume { get; set; }
        public Nullable<decimal> arrivalWeight { get; set; }
        public Nullable<decimal> arrivalVolume { get; set; }
    }
}
