//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domain
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransferOrderArrival
    {
        public long transferOrderArrivalId { get; set; }
        public long transferOrderId { get; set; }
        public long equipmentId { get; set; }
        public Nullable<decimal> scaleInWeight { get; set; }
        public Nullable<System.DateTime> scaleInDate { get; set; }
        public Nullable<decimal> scaleOutWeight { get; set; }
        public Nullable<System.DateTime> scaleOutDate { get; set; }
        public Nullable<decimal> netTransferWeight { get; set; }
        public string loadedEmptyStatus { get; set; }
        public bool isVoided { get; set; }
        public System.DateTime inputDate { get; set; }
        public string inputBy { get; set; }
        public System.DateTime modifiedDate { get; set; }
        public string modifiedBy { get; set; }
        public Nullable<System.DateTime> interfaceDate { get; set; }
        public Nullable<decimal> scaleInVolume { get; set; }
        public Nullable<decimal> scaleOutVolume { get; set; }
        public Nullable<decimal> netTransferVolume { get; set; }
        public Nullable<decimal> NetVolume { get; set; }
        public Nullable<short> ObservedTemperature { get; set; }
        public Nullable<int> sequenceNumber { get; set; }
    }
}
